### ISSUE TITLE
Could not find or load main class com.tomeraberbach.mano.application.Main

### ISSUE THREAD

**Issue by audioresearch74** [TomerADev/mano-simulator#5] opened 2021-03-18 13:57 UTC
fail to launch the application
this is the output:
~/Public/HelpFaceBookFriends2020/ManoSimulator$ java -jar mano-simulator.jar
Error: Could not find or load main class com.tomeraberbach.mano.application.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
~/Public/HelpFaceBookFriends2020/ManoSimulator$

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu219.10)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu219.10, mixed mode, sharing)

installed JDK and FX from synaptic (Ubuntu19.10)

how to fix this?

**Comment by TomerAberbach** [comment] 2021-03-18 14:46
Seems similar #4. I know you said you installed JavaFX, but are you sure? It seems it can't find a JavaFX related class. I think the package you need is `openjfx`.

Could also be related to this [bug](https://bugs.launchpad.net/ubuntu/+source/openjfx/+bug/1799946)? I don't remember if I've ever tested the simulator with JDK 11.

**Comment by audioresearch74** [comment] 2021-03-18 17:26
> Seems similar #4. I know you said you installed JavaFX, but are you sure? It seems it can't find a JavaFX related class. I think the package you need is `openjfx`.
> 
> Could also be related to this [bug](https://bugs.launchpad.net/ubuntu/+source/openjfx/+bug/1799946)? I don't remember if I've ever tested the simulator with JDK 11.

could it be I need to re-compile jar archive using jdk 11 so its format will fit java of jdk 11?

**Comment by TomerAberbach** [comment] 2021-03-19 03:45
Possibly. I probably won't have time to do that for a little while so you can either try to do it yourself or you can wait until I have time.

**Comment by karanmistry1804** [comment] 2021-04-26 18:57
> fail to launch the application
> this is the output:
> ~/Public/HelpFaceBookFriends2020/ManoSimulator$ java -jar mano-simulator.jar
> Error: Could not find or load main class com.tomeraberbach.mano.application.Main
> Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
> ~/Public/HelpFaceBookFriends2020/ManoSimulator$
> 
> openjdk version "11.0.7" 2020-04-14
> OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu219.10)
> OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu219.10, mixed mode, sharing)
> 
> installed JDK and FX from synaptic (Ubuntu19.10)
> 
> how to fix this?

Have you solve this error??

**Comment by TomerAberbach** [comment] 2021-04-27 01:25
Hey @audioresearch74 and @karanmistry1804. I found the time to make this work for Java 11+. Please try the new [release](https://github.com/TomerAberbach/mano-simulator/releases/tag/mano-simulator-1.0-SNAPSHOT) and let me know if it works!

**Comment by karanmistry1804** [comment] 2021-04-27 05:53
G:\karan mistry\DM>java -jar mano-simulator.jar
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing
QuantumRenderer: no suitable pipeline found
        at
com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at
com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)
        at
com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at
com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at
com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at
com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at
com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer:
no suitable pipeline found
        at
com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at
com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        ... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:273)
        at
com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at
com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at
com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at
com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at
com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:832)


This error is coming now.

**Comment by TomerAberbach** [comment] 2021-04-27 23:31
@karanmistry1804, I tweaked some stuff and uploaded a new JAR to the same release. Can you redownload and try again? Make sure you run `java -jar` on the new JAR!

**Comment by karanmistry1804** [comment] 2021-04-30 02:15
Thanks TomerAberbach/mano-simulator for helping me out .The new release
worked.

**Comment by TomerAberbach** [comment] 2021-04-30 03:43
No problem! I'm glad it's working for you now :smile: 

I'm going to close this issue @audioresearch74, but feel free to reopen if you run into any problems!

**Closed as completed by TomerAberbach** 2021-04-30 03:43 UTC
